export const STAFF_TYPE_LIST_REQUEST = "STAFF_TYPE_LIST_REQUEST";
export const STAFF_TYPE_LIST_SUCCESS = "STAFF_TYPE_LIST_SUCCESS";
export const STAFF_TYPE_LIST_FAIL = "STAFF_TYPE_LIST_FAIL";


export const STAFF_TYPE_DELETE_REQUEST = "STAFF_TYPE_DELETE_REQUEST";
export const STAFF_TYPE_DELETE_SUCCESS = "STAFF_TYPE_DELETE_SUCCESS";
export const STAFF_TYPE_DELETE_FAIL = "STAFF_TYPE_DELETE_FAIL";

export const STAFF_TYPE_CREATE_REQUEST = "STAFF_TYPE_CREATE_REQUEST";
export const STAFF_TYPE_CREATE_SUCCESS = "STAFF_TYPE_CREATE_SUCCESS";
export const STAFF_TYPE_CREATE_FAIL = "STAFF_TYPE_CREATE_FAIL";
export const STAFF_TYPE_CREATE_RESET = "STAFF_TYPE_CREATE_RESET";

export const STAFF_TYPE_EDIT_REQUEST = "STAFF_TYPE_EDIT_REQUEST";
export const STAFF_TYPE_EDIT_SUCCESS = "STAFF_TYPE_EDIT_SUCCESS";
export const STAFF_TYPE_EDIT_FAIL = "STAFF_TYPE_EDIT_FAIL";

export const STAFF_TYPE_UPDATE_REQUEST = "STAFF_TYPE_UPDATE_REQUEST";
export const STAFF_TYPE_UPDATE_SUCCESS = "STAFF_TYPE_UPDATE_SUCCESS";
export const STAFF_TYPE_UPDATE_FAIL = "STAFF_TYPE_UPDATE_FAIL";
export const STAFF_TYPE_UPDATE_RESET = "STAFF_TYPE_UPDATE_RESET";